#!/usr/bin/env python3
"""Collect every PLACEHOLDER marker into docs/PLACEHOLDERS.md.

One command answers "what's still fake?", which is the first question anyone
joining will ask.
"""

from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "PLACEHOLDERS.md"
MARKER = re.compile(r"PLACEHOLDER\(([^)]+)\):\s*(.*)")
SKIP = {"node_modules", ".venv", ".git", "dist", ".artifacts", ".logs", "sites"}
# .js is here for the Cloudflare Worker, which is the one piece of this
# system that runs somewhere else entirely -- and therefore the one most
# likely to be assumed working because nothing local complains.
EXTS = {".py", ".ts", ".tsx", ".js", ".yaml", ".yml"}


def main() -> None:
    findings: list[tuple[str, str, int, str]] = []

    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or path.suffix not in EXTS:
            continue
        if any(part in SKIP for part in path.parts):
            continue
        if path.name == "placeholders.py":
            continue
        try:
            lines = path.read_text().splitlines()
        except UnicodeDecodeError:
            continue
        for number, line in enumerate(lines, start=1):
            match = MARKER.search(line)
            if not match:
                continue
            # Keep the whole comment block, not just the first line -- the
            # useful half of a placeholder note is always the "why".
            note = [match.group(2).strip()]
            for follow in lines[number:]:
                stripped = follow.strip().lstrip("#").strip()
                if not stripped or MARKER.search(follow):
                    break
                if follow.strip().startswith("#"):
                    note.append(stripped)
                else:
                    break
            findings.append(
                (match.group(1), str(path.relative_to(ROOT)), number, " ".join(note))
            )

    OUT.parent.mkdir(exist_ok=True)
    body = [
        "# Placeholders",
        "",
        "Generated by `make placeholders`. Every entry is code that exists but has",
        "never run against the real thing, because the credential or vendor it needs",
        "is not available.",
        "",
    ]

    if not findings:
        body.append("_No placeholder markers found._")
    else:
        current = ""
        for integration, path, line, note in sorted(findings):
            if integration != current:
                current = integration
                body.append(f"\n## {integration}\n")
            body.append(f"- `{path}:{line}` -- {note}")

    body.append("")
    OUT.write_text("\n".join(body) + "\n")
    print(f"{len(findings)} placeholder marker(s) -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
